[package]
name = "open_pt3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
rexif = "0.7.3"
num_cpus = "1.13.1"
libmath = "0.2.1"
serde_json = "1.0.79"